### ISSUE TITLE
[Micro-service] Private IP manager

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#152]
**Summary**
The private IP manager is responsible of allocating and releasing private IP (within VPC/subnet) to a port. 

**User Cases**
The client of private IP manager could be 
(1) Subnet Manger who wants to allocate an IP for its gateway
(2) Port Manger who wants to allocate an IP for a port or a list of ports.

**Basic Requirements**
1. Allocate private IP address for all the ports, e.g., (Subnet 1, Port 1) → IP1
1. Release (port, IP) association when a port is released, or a port allocates a new IP
1. Guarantee uniqueness of IP address in a subnet scope.
1. Fall back mechanism if there is a conflict among IP addresses
1. Working together with other services including subnet manager and port manager.
1. Concurrency control mechanism should be provided to process multiple concurrent IP allocation requests.

**Advanced Requirements**
1. Support allocation and release of a list of IP addresses

**Comment by xieus** [comment]
This task is assigned to @chenpiaoping. Somehow the system doesn't support to assign this task to him.

**Comment by xieus** [comment]
@chenpiaoping Could you please make a comment on this ticket so that the system would allow me to assign it to you? Thanks.

**Comment by chenpiaoping** [comment]
Please assign this task to me, Thank you.

**Comment by xieus** [comment]
@chenpiaoping Assigned. Thank you!
