### ISSUE TITLE
Move database/cache module from legacy /src to /lib 

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#157]
We create a /lib folder to store common shared libraries across microservices. We need to move database and cache module to /lib so that microservices could start using Ignite.

**Comment by xieus** [comment]
@chenpiaoping Could you please make a comment on this ticket so that the system would allow me to assign it to you? Thanks.

**Comment by chenpiaoping** [comment]
Please assign this task to me, Thank you.

**Comment by xieus** [comment]
Assigned @chenpiaoping  Thank you!
