### ISSUE TITLE
[Documentation] Migration Plan for OpenStack Users

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#165]
**Basic Requirement**

Many OpenStack users are using Neutron as its networking control plane. This item is to lay out a migration plan from Neutron to Alcor, preferably with a few possible options.

Doc could go to https://github.com/futurewei-cloud/alcor/blob/master/docs/visionary_design/deployment.adoc

**Comment by Eric-Yuan** [comment]
I have some developing experience of Neutron, so I think I could do some work on this issue:)

**Comment by xieus** [comment]
That would be awesome. The ticket is assigned under your name @Eric-Yuan :-)
