### ISSUE TITLE
[Micro-Service] Data-plane manager

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#166]
**Summary**
The Data-plane manager is a control plane component responsible of driving network configuration down to the control agents installed on the physical hosts. It provides a flexible plugin framework which allows different data-plane extension.

**User Cases**
(1) Port Manger wants to send one new port information to every hosts in the VPC
(2) Security Group Manager wants to send one new security group to hosts in the VPC

**Basic Requirements**
1. Provide a flexible plugin framework which allows different data-plane extensions.
2. OVS extension supports integration with OVS
3. Reliably connecting to hosts through various paths including normal path (kafka) and fast path (gPRC)
4. Configurable retry mechanism when connection to hosts is unstable
5. Working together with other services including port manager and security group manager.
6. Concurrency control mechanism should be provided to process multiple concurrent network configuration programming requests.

**Advanced Requirements**
Fall back mechanism from one path to the other, for example, from fast path to normal path, or from normal path to rescue path

**Comment by haboy52581** [comment]
submit PR here: https://github.com/futurewei-cloud/alcor/pull/182. I would work on the design doc now.

**Comment by haboy52581** [comment]
added the design doc

**Comment by haboy52581** [comment]
updated the design doc with one new diagram and answered some key questions
