### ISSUE TITLE
Integration with Nova Compute (in the vm creation scenario)

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#190]
__Integration Story__

Currently OpenStack allows users to launch VM instance via Horizon Dashboard or run nova boot command via OpenStack CLI. When it occurs, Nova compute would trigger a few REST calls to Neutron to allocate necessary network resources. We would want to integrate Nova to support the same set of user operations, especially the vm creation scenario.

__Requirements__
* Identify all necessary changes (configuration and/or codes) in Nova to call Alcor REST APIs, instead of Neutron APIs
* Make a proposal that requires minimal Nova changes 
* Implement the code/configuration change
* Deploy and test the change in a multi-node OpenStack cluster

**Comment by xieus** [comment]
@Gzure Are you interested in giving this item a try? Please respond to the issue so that we could assign it to you (per GitHub policy). Thanks in advance for your contribution.

**Comment by Gzure** [comment]
I have try it. And I identify all necessary changes (configuration and/or codes) in Nova to call Alcor REST APIs.

**Comment by Gzure** [comment]
Sorry,I repled in slack. I have try it.I have identifed all necessary APIS in Nova to call Neutron REST APIs.

**Comment by Gzure** [comment]
I'm working on it.I have identifed all necessary APIS in Nova to call Neutron REST APIs.

**Comment by xieus** [comment]
That is very nice @Gzure Thank you.
