### ISSUE TITLE
[New API] Route Manager to support GET routes by subnet Id

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#203]
__Context__

Route manager currently only support route retrieval by VPC ID. Port Manager would need to GET route API by subnet ID in the port creation scenario. We would love to have this API in place.

**Comment by xieus** [comment]
@kevin-zhonghao Could you please help to add this API? Thanks.

**Comment by kevin-zhonghao** [comment]
I have added the GET route API by subnet Id in route manager (value = {"/subnets/{subnetId}/routes/{routeId}"}))
If there is no this API in route manager, it will be merged in my current PR

**Comment by xieus** [comment]
Thanks @kevin-zhonghao for the quick turnaournd.

**Comment by xieus** [comment]
The added API "/subnets/{subnetId}/routes/{routeId}" still requires to pass a routeId. The original request was to query routes by subnet id, without passing any routeId.
