### ISSUE TITLE
API Gateway A&A support and Integration with OpenStack KeyStone

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#207]
__Integration Story__

Alcor API currently requires a project id in the API Url. Neutron 2.0 APIs, however, don't need to provide a project id as it generates the project id based on the Authentication token in the X-Auth-Token request header, when Keystone is enabled.

Reference: https://docs.openstack.org/api-ref/network/v2/
"The Networking API v2.0 uses the OpenStack Identity service as the default authentication service. When Keystone is enabled, users that submit requests to the OpenStack Networking service must provide an authentication token in X-Auth-Token request header. You obtain the token by authenticating to the Keystone endpoint.

When Keystone is enabled, the project_id attribute is not required in create requests because the project ID is derived from the authentication token."

__Requirements__
* Identify Neutron's algorithm that generates project id based on X-Auth-Token.
* Make changes to API Gateway to support Authentication & Authorization with KeyStone, and support same way how project id is generated based on X-Auth-Token in API Gateway.
* Integration testing with KeyStone.

**Comment by xieus** [comment]
@Gzure, could you please acknowledge on this feature request? Thank you.

**Comment by Gzure** [comment]
Yes,I will follow this request.
