### ISSUE TITLE
[Microservice] Elastic IP Manager

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#214]
**Summary**
The Elastic IP (EIP) manager is responsible of allocating and releasing EIP as well as  associating the allocated EIP to a running instance or network interface (port). This is the acting microservice that provides elastic/floating IP APIs to external customers (through API gateway) and driving the elastic IP CURD workflow. A network interface with an enabled EIP could establish inbound connections from and outbound connections to external networks like Internet.

**User Cases**
A customer of Alcor could leverage Elastic IP manager in the following cases:
(1) Allocate or release a _standalone_ EIP within the user account.
(2) Associate or disassociate an EIP to a running instance, which by default attach to its primary interface.
(3) Associate or disassociate an EIP to a network interface.

**Basic Requirements**
1. Provide CURD REST APIs for customers or provider admins to management EIPs. The APIs are compatible to OpenStack Neutron v2.0 APIs (Ref: https://docs.openstack.org/api-ref/network/v2/?expanded=#list-floating-ips).
1. Provide CURD REST APIs for cloud provider admins to register or unregister a list of public IPv4 or IPv6 ranges in EIP manager.
Note that those IP ranges should be owned by cloud provider.
1. Allocate _standalone_ and _unique_ EIP address. Guarantee uniqueness of EIP address in a regional scope.
1. Release public IP address per customer request or other microservices, and make it ready for reuse for other customers.
1. Release (port, EIP) association when a port is to be deleted.
1. Maintain EIP states and a mapping from an EIP to its owning interface/port.
1. Association of an EIP to a running instance or network interface (port) at POST call (when fixed_ip_address is not NULL), or at PUT call.
1. Disassociation of EIP with a network interface (primary or secondary).
1. Working together with other services including port manager and DNS manager for allocation of port and external DNS, respectively.
1. Concurrency control mechanism should be provided to process multiple concurrent EIP allocation requests.

**Advanced Requirements**
1. Support bulk allocation and release of a list of IP addresses.
1. Support BYOIP to allow customers to bring existing public IPv4 address range or IPv6 address range from their on-premises network to Alcor.

**Comment by Eric-Yuan** [comment]
Might this issue could be assigned to me?

**Comment by xieus** [comment]
Definitely. That would be perfect!
