### ISSUE TITLE
[Ignite] Support Batch Insertion

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#226]
__Request__

* In ICacheRepository, add a new interface named _addItems_ which allows add a list of items to Ignite DB/Cache
* Add the new method in all the repo child classes among all microservices
* Enable batch insertion in PortManager

**Comment by xieus** [comment]
@chenpiaoping created item in case we forget. So many features and pending items here and there :-)

**Comment by xieus** [comment]
@chenpiaoping Does the recent change in PM solve this request? This appear not that urgent for now. We may need to revisit this issue sooner than later though.

**Comment by chenpiaoping** [comment]
> change in PM solve this requ

ICache has provided putAll () interface, but ICacheRepository has not provided addItems () interface.
