### ISSUE TITLE
[AlcorCommonLib] Allow partial rollback under the current rollback framework 

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#228]
__Context__

The current rollback framework would revert all operations if there is one failed operation. In certain scenarios of resource creation, we do want to support partial rollback of failed operations and associated resources, but let the successful operations continue and persist.

__Requirements__
* Add a allow_partial parameter in the rollback framework
* When true, the return response includes the details of those resources if created successfully and detailed error codes otherwise.

**Comment by xieus** [comment]
@chenpiaoping For your own tracking.

**Comment by chenpiaoping** [comment]
Fixed
