### ISSUE TITLE
[Port Manager] Use IP/Mac replacement APIs for port update

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#229]
__Request__

After IP Manager (Issue https://github.com/futurewei-cloud/alcor/issues/218) and Mac Manager (Issue https://github.com/futurewei-cloud/alcor/issues/217) provide replacement APIs, we would like to use the new APIs for port update to allow "atomic" operation.

**Comment by xieus** [comment]
@chenpiaoping For you tracking purpose.

**Comment by chenpiaoping** [comment]
Finished
