### ISSUE TITLE
[SGM] Port-SG binding triggered by bulk port creation API failed due to terminated Ignite Transaction

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#264]
__Context__

When we trigger bulk port creation API, it would trigger concurrent port creation operation which results in port-SG binding into the SGM. In the test of deploying four ports into two hosts, each host with two ports, we frequently hit the following Ignite issue.

com.futurewei.alcor.common.db.CacheException: Ignite failed to process request: Transaction with id xx not found (server status code [1021])

**Comment by chenpiaoping** [comment]
@xieus Can you add synchronized to the addSecurityGroypBinding method, and then try again? like this:
public synchronized  void addSecurityGroypBinding()

**Comment by xieus** [comment]
Definitely @kevin-zhonghao could try to add it as part of integration test.

Could the mentioned scenario be tested in our SGM or PM UTs? If so, it might be actually a better idea for us to add more UTs there to cover concurrency issues.
