### ISSUE TITLE
[DPM] UT enhancement for core logic

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#288]
__Context__

The DPM UTs currently cover the GSManager only. We will also need to cover the controller layer and others. 

Please leverage the code coverage report to cover more core logic: https://codecov.io/gh/futurewei-cloud/alcor/tree/f0bcc66f4256ffb75859fc91019bf56bbd68629d/services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane

**Comment by haboy52581** [comment]
added in 1f5ffa3, would add more

**Comment by xieus** [comment]
@kevin-zhonghao for awareness.

**Comment by haboy52581** [comment]
per the context "The DPM UTs currently cover the GSManager only. We will also need to cover the controller layer and others.
" , @kevin-zhonghao please add this part for controllers
