### ISSUE TITLE
[VMN] Mac Range Selector

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#302]
__Context__

In the currently Mac Mgr implementation, there is a concept of default range from which each allocation request will get address. This default range could become a bottleneck when there are significant load in a region therefore we could consider to replace "default range" with a range selector.

__Proposal__

In the MacRangeRepository or a new repository, create a table to track the utilization of each range.

__Option 1 Explicit update__:
Every allocation request always goes to that table to pick up the latest range with least utilization, and increment the count after an allocation request or decrease the count after a release request.
This option is easy to implement at a cost of write performance (more DB access!).

__Option 2 In-Memory Counter with Background Monitoring__:
Each Mac Manager Instance has an in-memory counter that tracks the utilization of each range. The counter gets updated by a running monitoring thread in a periodic manner. This thread should run not very frequently, say every 30 minutes or so, and keep the counter always up-to-date. The allocation/release request only needs to read the in-memory counter but no obligation to update it.

NOTE that when every Mac Manager instance launches or restart, it also needs to initialize its in-memory counter.

**Comment by xieus** [comment]
@Gzure Please take the lead on this item.

**Comment by Gzure** [comment]
The Default range begins with a fixed prefix XX-XX-XX and ends with the maxium in the range. So it includes all macs. Do we need create  few of ranges from the default ranges If we replace the default range to a range selector ? If so should we remain the create range rest api?

**Comment by xieus** [comment]
This new performance enhancement has been offered by PR #292 and this issue is considered as closed.
