### ISSUE TITLE
[Node Manager] Upload API doesn't support batch node registration 

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#303]
__Context__

The Node Mgr API /nodes/upload doesn't meet the design goal of registering multiple nodes in one shot. The required format of machine.json file is as follows:

```json
{
   "Hosts": [
      {
         "local_ip": "10.213.43.01",
         "node_id": "cc09465c-5ed6-400e-806d-fbe3d12f94a9",
         "mac_address": "00:A0:C9:14:C8:29",
         "node_name": "Compute1",
         "server_port": 50001,
         "veth": "eth0"
      },
      {
         "local_ip": "10.213.43.02",
         "node_id": "a976fe8a-2ebc-4d8b-9750-a6ec31b9680e",
         "mac_address": "00:A0:C9:14:C8:3A",
         "node_name": "Compute2",
         "server_port": 50001,
         "veth": "eth0"
      },
      ......
      {
         "local_ip": "10.213.43.19",
         "node_id": "7fa7f9b8-8ce5-4c61-9a09-a739eeb965ac",
         "mac_address": "00:A0:C9:14:C8:4F",
         "node_name": "Compute19",
         "server_port": 50001,
         "veth": "eth0"
      }
   ]
}
```

__Request__

Code and UT fix

**Comment by kimeunju108** [comment]
Hello Liguang,

I saw the following email.  Just FYI, when the Node Mgr API /nodes/upload was tested, it was fine. It looks like the reason it doesn’t work now may be the difference of machine.json.  I hope this helps you fix this issue.
Tested machine.json was in  services/node_manager/test/java/com.futurewei.alcor.nodenamaner/controller/machine.json. Previous file format was as fiollows:

{
  "Hosts": [
    {
      "id": "ephost_0",
      "ip": "172.17.0.6",
      "mac": "02:42:ac:11:00:06",
      "veth": {}
    },
    {
      "id": "ephost_1",
      "ip": "172.17.0.7",
      "mac": "02:42:ac:11:00:07",
      "veth": {}
    },
    {
      "id": "ephost_2",
      "ip": "172.17.0.8",
      "mac": "02:42:ac:11:00:08",
      "veth": {}
    },
    {
      "id": "ephost_3",
      "ip": "172.17.0.9",
      "mac": "02:42:ac:11:00:09",
      "veth": {}
    },
    {
      "id": "ephost_4",
      "ip": "172.17.0.10",
      "mac": "02:42:ac:11:00:0a",
     "veth": {}
    },
    {
      "id": "ephost_5",
      "ip": "172.17.0.11",
      "mac": "02:42:ac:11:00:0b",
      "veth": {}
    },
    {
      "id": "ephost_6",
      "ip": "172.17.0.12",
      "mac": "02:42:ac:11:00:0c",
      "veth": {}
    },
    {
      "id": "ephost_7",
      "ip": "172.17.0.13",
      "mac": "02:42:ac:11:00:0d",
      "veth": {}
    },
    {
      "id": "ephost_8",
      "ip": "172.17.0.14",
      "mac": "02:42:ac:11:00:0e",
      "veth": {}
    },
    {
      "id": "ephost_9",
      "ip": "172.17.0.15",
      "mac": "02:42:ac:11:00:0f",
      "veth": {}
    }
  ]
}

**Comment by xieus** [comment]
@kimeunju108 Thanks for providing the information. 

Actually the TEST machine.json as your pointed out was actually tested first for POST /nodes/upload. But the API throws the following exception:

java.lang.ClassCastException: class org.json.simple.JSONObject cannot be cast to class java.lang.String

After trying a Json with the same Json format as that in POST /nodes, it would work but that only allows one node registration.
