### ISSUE TITLE
[CI] JAVA CI workflow is unstable - SwaggerJsonTest test case fails from time to time

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#312]
__Context__

JAVA CI workflow sometimes have test failure which can only be reproduced in Ubuntu and MacOSX, but not in Windows OS. An example: PR https://github.com/futurewei-cloud/alcor/pull/311 https://github.com/futurewei-cloud/alcor/pull/312

EIP Manager has one test case failure from time to time:
[ERROR] Errors:
[ERROR] SwaggerJsonTest.createSpringfoxSwaggerJson » IllegalState Failed to load Appli...
[INFO]
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 0

- Possible Cause 1:
https://github.com/futurewei-cloud/alcor/blob/master/.github/workflows/maven.yml relies on a test script https://github.com/futurewei-cloud/alcor/blob/master/scripts/test-prep.sh which is using JDK 8 to build Ignite container. 
- Possible Cause 2:
SwaggerJsonTest code bug

__Request__

Investigate the test failure and upgrade test script/codes.

**Comment by xieus** [comment]
@Eric-Yuan Could you please take a look at this issue quickly to see if a EIP Mgr test code issue? Thank you.

**Comment by Eric-Yuan** [comment]
Yes, I could work on it

**Comment by xieus** [comment]
Thank you @Eric-Yuan
