### ISSUE TITLE
Port Manager should support vif_type config for integrate with nova. 

### ISSUE THREAD

**Issue by Gzure** [futurewei-cloud/alcor#319]
Nova creates a VM need a vif_type to start an instance. But now this field is null. I added a default value "ovs". We should  implement vif_type in future.

**Comment by xieus** [comment]
Issue is partially resolved by PR #320. Would need to a follow-up PR to have full vif_type support E2E. 

FYI @er1cthe0ne Need some agent input here.

**Comment by er1cthe0ne** [comment]
> Issue is partially resolved by PR #320. Would need to a follow-up PR to have full vif_type support E2E.
> 
> FYI @er1cthe0ne Need some agent input here.

For vif_type, are we talking about the virtual NIC for the VM that could be OVS or Linux Bridge or vhostuser etc? If that's the case, defaulting to OVS is good for now. Will need to understand the need to support which vif_type on the E2E.

BTW, who decide which vif_type to use for the VM? Is it based on the VM type and/or customer selected option?

**Comment by xieus** [comment]
> For vif_type, are we talking about the virtual NIC for the VM that could be OVS or Linux Bridge or vhostuser etc? If that's the case, defaulting to OVS is good for now. Will need to understand the need to support which vif_type on the E2E.

We referred to the type of mechanism that Alcor's API consumer (like Nova) will use to determine an appropriate way to attach a device (e.g. an interface of a virtual server) to the port. 

Agreed "ovs" as a default value of "vif_type". Currently, available values defined in the controller include ovs, bridge, macvtap, vhostuser etc.

There are a few values that Neutron supports as of now which are a bit of special including hw_veb, hostdev_physical, distributed. We can discuss whether we would need to support those values.

> BTW, who decide which vif_type to use for the VM? Is it based on the VM type and/or customer selected option?

This field is part of port binding attributes which are usually determined by administrative users in Neutron, not regular users. When an admin user sets up a cloud, it would have the opportunity to configure all kinds of these values.

**Comment by xieus** [comment]
@er1cthe0ne Can you pls check the latest status for this issue?

**Comment by er1cthe0ne** [comment]
> @er1cthe0ne Can you pls check the latest status for this issue?

Not update on this yet. I am curious to know the importance for Alcor to support other ways to attach a device other than OVS (e.g. bridge, macvtap, hw_veb, hostdev_physical, vhostuser, etc). @Gzure what do you think?

The next step is to update DPM<->ACA contract under port.proto to add vif_type in PortConfiguration. It doesn't have it yet.

**Comment by xieus** [comment]
Discussed this in the open-source community meeting. The need of supporting VLAN + Linux bridge is low due to lack of customer requirement. Will close this issue for now and revisit when needed.
