### ISSUE TITLE
[Enhancement] Alcor Distributed Router Enhancement

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor#375]
Currently, Alcor Distributed Router relies on a host unique distributed router mac address to enable the L3 routing E2E. We want to investigate enhancement to see if there is a way deal with it without programming the each port about their neighbor port's host distributed router mac address.

**Comment by xieus** [comment]
@Eric-Yuan Remember you did mention some pretty good improvement in this week's meeting. Can you give a bit more details here? Thanks!

**Comment by Eric-Yuan** [comment]
In tenant networks, all the mac addresses are allocated by the cloud platform, so we could reserved a specified address prefix for the DVR host mac scope, for example a 3 bytes long prefix FE:16:11. If we do so, we could only match the prefix of src mac address and vlan id,  to decide which GW mac address should be used to transform.

**Comment by er1cthe0ne** [comment]
> In tenant networks, all the mac addresses are allocated by the cloud platform, so we could reserved a specified address prefix for the DVR host mac scope, for example a 3 bytes long prefix FE:16:11. If we do so, we could only match the prefix of src mac address and vlan id, to decide which GW mac address should be used to transform.

That's cool. I got the idea. It would be the same approach if we match the src mac address and VNI (vxlan tunnel id) right?

Let me look into the the current ACA code to see how we can apply this idea. Thanks!

**Comment by Eric-Yuan** [comment]
Sure, it depends which table we put the tranform process, we can use VNI to match if this process before the tranform process between VNI and local vlan. You are welcome:)

**Comment by er1cthe0ne** [comment]
@Eric-Yuan - I have confirmed this approach can work in ACA. Thanks again for the suggestion
