### ISSUE TITLE
[Scalability Test] Part 1: DPM performance test report

### ISSUE THREAD

**Issue by Gzure** [futurewei-cloud/alcor#399]
This issue for DPM test result report.

Setup as follows:
- DPM + simulated ACA
- 1M simulated nodes
- large VPC up to 100K ports

Messaging channel
- gRPC
- Pulsar

**Comment by Gzure** [comment]
base on old DPM test:
server: 
cpu: 2 * Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz (16core, open super thread)
memory: 8*32G 2400MHz
storage: 8*32G 2400MHz
network: 25GE

controller node: 3xserver k8s
compute node: 20xserver 

1 DPM 1port message 
neighbor: 1 msg-latency:7ms all-latency:12ms
neighbor: 100 msg-latency:24ms all-latency:12
neighbor: 1000 msg-latency:185ms all-latency:373ms
neighbor: 10k msg-latency:2584ms all-latency:5147ms
neighbor: 20k msg-latency:4612ms all-latency:9861ms
neighbor: 40k msg-latency:9374ms all-latency:19091ms
neighbor: 80k msg-latency:18822ms all-latency:38044ms
neighbor: 160k msg-latency:38015ms all-latency:77524ms
neighbor: 320k msg-latency:79998ms all-latency:159914ms
neighbor: 640k msg-latency:155004ms all-latency:325697ms
neighbor: 1M msg-latency:242256ms all-latency:504842ms

1DPM 10k neighbor
2 port request latency:5657ms
2 port request latency:5657ms

**Comment by xieus** [comment]
Awesome. Thanks @Gzure 

After PR #425 in, let us measure the latency again and show a follow-up comparison report.

**Comment by xieus** [comment]
Linked to umbrella issue #439

**Comment by xieus** [comment]
Performance report reviewed. Issue closed.
