### ISSUE TITLE
[Test] Break down ACA mega tests based on module

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#416]
__Background & Requests__

ACA currently has mega test files which is nearly 3K lines of codes. We prefer to have a short test case based on module which is easier for us to search for existing test cases and create new test cases.

**Comment by xieus** [comment]
As we expect more engineers to join ACA development, an improved test framework will expedite the process.

**Comment by er1cthe0ne** [comment]
Fixed in https://github.com/futurewei-cloud/alcor-control-agent/pull/153
