### ISSUE TITLE
Openstack subnet show got error "'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by cj-chung** [futurewei-cloud/alcor#428]
Openstack subnet show <subnet _id> got error: `'NoneType' object is not iterable`.
Using Openstack horizon to show subnet also got 
`Danger: An error occurred. Please try again later. `

**Comment by xieus** [comment]
Impact Horizon UI and CLI.

**Comment by cj-chung** [comment]
The contract returned by subnet manager is incorrect. 
1) Modify following fields in the subnet entity to array: `dns_nameservers`, `service_types` and `host_routes`. 
2) Modify `start_ip` and `end_ip` in the `application_pools` field to `start` and `end`.

**Comment by kevin-zhonghao** [comment]
The PR solved this issue is the following:
https://github.com/futurewei-cloud/alcor/pull/438
