### ISSUE TITLE
[Port Manager] Support router and user-defined route

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#434]
__Contract__

RM InternalRouterInfo: https://github.com/futurewei-cloud/alcor/blob/290e3354905c88a31f2aa6ab3c00073458dc48fd/web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRouterInfo.java

NMM NodeInfo: https://github.com/futurewei-cloud/alcor/blob/290e335490/web/src/main/java/com/futurewei/alcor/web/entity/NodeInfo.java

DPM InternalRouterInfos: https://github.com/futurewei-cloud/alcor/blob/master/web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java

**Comment by xieus** [comment]
@chenpiaoping Do you have bandwidth to take this item? If your hands are too full, I could take this item. Let me know.

**Comment by chenpiaoping** [comment]
> @chenpiaoping Do you have bandwidth to take this item? If your hands are too full, I could take this item. Let me know.

I am busy with the implementation of the security group on the ACA side, and it would be great if you have time to do it.

**Comment by xieus** [comment]
> > @chenpiaoping Do you have bandwidth to take this item? If your hands are too full, I could take this item. Let me know.
> 
> I am busy with the implementation of the security group on the ACA side, and it would be great if you have time to do it.

Okay. I will take on the challenge then :-) 

Btw, is the old com.futurewei.alcor.portmanager.service.implement.PortServiceImpl ready to get deprecated?

**Comment by chenpiaoping** [comment]
> > > @chenpiaoping Do you have bandwidth to take this item? If your hands are too full, I could take this item. Let me know.
> > 
> > 
> > I am busy with the implementation of the security group on the ACA side, and it would be great if you have time to do it.
> 
> Okay. I will take on the challenge then :-)
> 
> Btw, is the old com.futurewei.alcor.portmanager.service.implement.PortServiceImpl ready to get deprecated?

yes

**Comment by xieus** [comment]
This issue is resolved by PR https://github.com/futurewei-cloud/alcor/pull/446
