### ISSUE TITLE
[DPM] Tunnel ID missing when converting message from NB to SB

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#443]
__Bug Description__

Tunnel id is passed in the InternalSubnetEntity from PM to DPM, and then passed down to ACA for host tunnel initialization during port creation. It is likely that one bug in latest DPM L3 code (PR #418) causes the lost of tunnel id when converting message from NB to SB GS message. The GS message, however, was sent down to ACA. ACA caught the input issue and returned an INVALID_ARG error as expected. 

__Request__
- Fix the missing tunnel id
- Check related fields to make sure no fields are lost during message conversion

__DPM Input__
```
"subnets_internal": [
  {
    "id": "b0cce82a-5e66-4bf0-87f5-1e29832161c2",
    "project_id": "5ddc6d5e405f4a8b8665bf2e812284f0",
    "tenant_id": "5ddc6d5e405f4a8b8665bf2e812284f0",
    "name": "admin1-subnet3",
    "description": null,
    "network_id": "fe05e2db-0b7b-4290-93db-9dfb61483747",
    "cidr": "192.168.3.0/24",
    .....
    "created_at": "2020-10-22 03:52:04",
    "updated_at": "2020-10-22 03:52:04",
    "tunnel_id": 8552448
  }
]
...
```

__DPM Output__
```
10.213.43.99=subnet_states {
  operation_type: INFO
  configuration {
    format_version: 1
    id: "b0cce82a-5e66-4bf0-87f5-1e29832161c2"
    project_id: "5ddc6d5e405f4a8b8665bf2e812284f0"
    vpc_id: "fe05e2db-0b7b-4290-93db-9dfb61483747"
    cidr: "192.168.3.0/24"
  }
}
...
```

__Response from ACA__
```
2020-10-22 03:53:03.756  INFO 1 --- [pool-1-thread-1] global                                   : GS #0:resource_id: "5f663b74-103e-427d-8c0f-7b3985934bc9"

resource_type: PORT
operation_status: INVALID_ARG
state_elapse_time: 240662

2020-10-22 03:53:03.756  INFO 1 --- [pool-1-thread-1] global                                   : GS #1:resource_id: "NA_ID"
resource_type: DHCP
state_elapse_time: 79128
```

**Comment by haboy52581** [comment]
here is NO tunnel_id even in the SubnetEntity of web, did a quick fix in 254b4bf for now

**Comment by haboy52581** [comment]
this is fixed in 72130

**Comment by xieus** [comment]
__Root Cause__
The issue was caused by an wrong entity class used in DPM internal implementation. 
In the DPM contract https://github.com/futurewei-cloud/alcor/blob/d0df82925dd60304230a4548724aeaeedebeee8f/web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java#L39 InternalSubnetEntity is in use and includes the tunnel id. However, DPM internal implementation uses a smaller set of entity class -- SubnetEntity -- thus caused the issue.

**Comment by haboy52581** [comment]
not getting you, so as I said it is already fixed in 72130 commit , actually it is fixed in 05b7 on Oct 22nd , do you want to close it?

**Comment by xieus** [comment]
Right. The issue will be closed once the commit is merged to master. PR #418 remains active.
