### ISSUE TITLE
[Port manager] Remove the usage of deprecating NEIGHBOR_CREATE_UPDATE and NEIGHBOR_DELETE in schema

### ISSUE THREAD

**Issue by er1cthe0ne** [futurewei-cloud/alcor#462]
**Context**

We are deprecating NEIGHBOR_CREATE_UPDATE and NEIGHBOR_DELETE from our schema in common.proto:

enum OperationType {
    CREATE = 0;
    UPDATE = 1;
    GET = 2;
    DELETE = 3;
    INFO = 4;
    NEIGHBOR_CREATE_UPDATE = 5; // To be removed after using NeighborState
    NEIGHBOR_GET = 6;           // To be removed after using NeighborState
    NEIGHBOR_DELETE = 7;        // To be removed after using NeighborState
}

It was originally there when DPM<->ACA overloaded portConfiguration to communicate neighbor information. It has been switched to use the new neighborConfiguration (in neighbor.proto) for cleaner and clearer message.

Somehow port manager is using NEIGHBOR_CREATE_UPDATE and NEIGHBOR_DELETE in PortServiceImpl.java:

    @Override
    @DurationStatistics
    public RouterUpdateInfo updateL3Neighbors(String projectId, RouterUpdateInfo routerUpdateInfo) throws Exception {
        List<NeighborInfo> neighborInfos = new ArrayList<>();
        List<NeighborEntry> neighborTable = updateNeighborTable(routerUpdateInfo, neighborInfos);

        if (neighborTable.size() > 0) {
            NetworkConfiguration networkConfiguration = new NetworkConfiguration();
            networkConfiguration.setRsType(Common.ResourceType.NEIGHBOR);
            String operationType = routerUpdateInfo.getOperationType();
            if (RouterUpdateInfo.OperationType.ADD.getType().equals(operationType)) {
                networkConfiguration.setOpType(Common.OperationType.NEIGHBOR_CREATE_UPDATE);
            } else {
                networkConfiguration.setOpType(Common.OperationType.NEIGHBOR_DELETE);
            }
            networkConfiguration.setNeighborInfos(neighborInfos);
            networkConfiguration.setNeighborTable(neighborTable);
            new UpdateNetworkConfigRequest(null, networkConfiguration).send();
        }

        return routerUpdateInfo;
    }

**Action Item**

use Common.OperationType.CREATE instead of Common.OperationType.NEIGHBOR_CREATE_UPDATE
use Common.OperationType.DELETE instead of Common.OperationType.NEIGHBOR_DELETE

Without the above change, it will generate the below compile time error when NEIGHBOR_CREATE_UPDATE and NEIGHBOR_DELETE is removed in the schema:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project portmanager: Compilation failure: Compilation failure: 
[ERROR] /Users/ericli/dev/alcor-dev/services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java:[261,68] cannot find symbol
[ERROR]   symbol:   variable NEIGHBOR_CREATE_UPDATE
[ERROR]   location: class com.futurewei.alcor.schema.Common.OperationType
[ERROR] /Users/ericli/dev/alcor-dev/services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java:[263,68] cannot find symbol
[ERROR]   symbol:   variable NEIGHBOR_DELETE
[ERROR]   location: class com.futurewei.alcor.schema.Common.OperationType
[ERROR] -> [Help 1]

**Comment by chenpiaoping** [comment]
It will be fixed in this commit.: https://github.com/futurewei-cloud/alcor/pull/512/commits/67701a0a5492806049b9a406cf332bac5a177833
