### ISSUE TITLE
[Component Upgrade] Upgrade to Ignite 2.9 for better support of cluster management, distributed tracing 

### ISSUE THREAD

**Issue by xieus** [futurewei-cloud/alcor#476]
__Context__

Apache Ignite announced a new release v2.9 on late October, 2020, with a few useful features
- Cluster Snapshots 
- Tracing
- New feature available for Java-based thin client including cluster discovery, cluster API, compute API, and service invocation support

These features will be useful to Alcor's next step and enable cache/db tracing to Alcor's tracing framework.

https://blogs.apache.org/ignite/entry/apache-ignite-2-9-released

__Request__
Let us plan to upgrade Ignite version from 2.8.1 to 2.9.
- Deploy Ignite 2.9 to Alcor Stage cluster
- Validate basic functionality
- Run performance test suite to ensure there is no performance regression, both components and E2E.
- Monitor CPU/memory/IO usage for Ignite services under v2.9.

**Comment by songxiaoyan** [comment]
learning~

**Comment by xieus** [comment]
ETA: 12/04 based on open-source meeting discussion.
