### ISSUE TITLE
[PM] Refactor update-l3-neighbors API to accept a list of gateway port IDs

### ISSUE THREAD

**Issue by cj-chung** [futurewei-cloud/alcor#506]
**Description:**
The current `update-l3-neighbors` API in PM accepts a list of subnet IDs from RM to construct L3 neighbor information. In this way, RM needs to ask SM about the subnet-id for each gateway port in RM. It causes more API calls from RM to SM just for subnet-id list.

In the current implementation, the gateway port of a subnet is created by PM, so PM has port-id and its subnet-id mapping.

Existing design: https://github.com/futurewei-cloud/alcor/blob/master/docs/modules/ROOT/pages/mgmt_services/route_manager.adoc#for-case-5-add-or-delete-a-gateway-port-for-neutron-only

New design: see the new diagram below

**Propose Solution:**
Refactor PM's `update-l3-neighbors` API to accept a list of gateway port id from RM, get corresponding subnet-ids and construct L3 neighbors info in PM directly.

**Comment by xieus** [comment]
We will need change in RM and SM meanwhile.

**Comment by cj-chung** [comment]
![image](https://user-images.githubusercontent.com/66383484/101523586-a6410780-393d-11eb-81da-f49c254c8edc.png)

**Comment by xieus** [comment]
@chenpiaoping In the API #5,  its body used to include a list of connected subnet ids. We plan to update it with a list of gateway port ids. 

Step #6 is also new to PM. (Note that we've change the gateway port creation logic. As of now, when a subnet is created, SM calls PM to create a gateway port. Therefore we have an unified management of both gateway ports and non-gateway ports)

**Comment by chenpiaoping** [comment]
@xieus Thank you for your detailed description. 
@cj-chung Can you update the key workflows in route's design doc?
