### ISSUE TITLE
[Port Mgr Cache] Failed to delete Subnet Entity, throwing exception gateway port not found

### ISSUE THREAD

**Issue by kevin-zhonghao** [futurewei-cloud/alcor#522]
**Step to Reproduce Issues:**
1. If you create a subnet S1, subnet mgr calls private IP mgr to register an IP range R1 and calls port manager to allocate an gateway port P1.  Checking P1 status is activated in the IP Manager;
2. Delete the subnet S1.
3. Recreate subnet S1 with the SAME subnet Id. There will be a new IP Range R2 for the subnet, but in the IP Manager, the gateway ip status under the new IP range R2 is free; the gateway ip status under the old IP range R1 is activated. And when deleting the subnet failed, it throws the gateway port not found exception

**Exception in Subnet Mgr:**
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":"2020-12-19T02:30:03.918+0000","status":500,"error":"Internal Server Error","message":"org.springframework.web.client.HttpClientErrorException$NotFound: 404 : [{\"timestamp\":\"2020-12-19... (473 bytes)]] with root cause

**Payload of creating subnet:**
{
  "subnet": {
    "cidr": "10.0.0.0/24",
    "id": "9192a4d4-ffff-4ece-b3f0-8d36e3d88000",
    "ip_version": 4,
    "network_id": "9192a4d4-ffff-4ece-b3f0-8d36e3d88038",
    "name": "subnet1"
  }
}

---
**Analysis:**
This issue may be related to the Cache in PM. There may be a mapping between subnet id and IP range id in PM.

**Comment by xieus** [comment]
@chenpiaoping Could you pls take a quick look at the stale cache issue?

**Comment by xieus** [comment]
> 3\. Recreate subnet S1 with the SAME subnet Id. There will be a new IP Range R2 for the subnet, but in the IP Manager, the gateway ip status under the new IP range R2 is free; the gateway ip status under the old IP range R1 is activated. And when deleting the subnet failed, it throws the gateway port not found exception

@chenpiaoping I saw your fix in PR #536 for subnet mgr. Were you able to reproduce the issue following the above steps?

**Comment by chenpiaoping** [comment]
> > 3. Recreate subnet S1 with the SAME subnet Id. There will be a new IP Range R2 for the subnet, but in the IP Manager, the gateway ip status under the new IP range R2 is free; the gateway ip status under the old IP range R1 is activated. And when deleting the subnet failed, it throws the gateway port not found exception
> 
> @chenpiaoping I saw your fix in PR #536 for subnet mgr, which should address issue #523 for Subnet Mgr. For Issue #522, were you able to reproduce the issue following the above steps?

For the third step, the gateway ip status under the old IP range and new ip range are activated.
[{"ip_version":4,"vpc_id":null,"subnet_id":null,"range_id":"a9d61427-f606-4af1-9314-04b5713bcd74","ip":"10.0.0.2","state":"activated"},
{"ip_version":4,"vpc_id":null,"subnet_id":null,"range_id":"a9d61427-f606-4af1-9314-04b5713bcd74","ip":"10.0.0.1","state":"activated"}]

**Comment by chenpiaoping** [comment]
but the old gateway is 

> > 3. Recreate subnet S1 with the SAME subnet Id. There will be a new IP Range R2 for the subnet, but in the IP Manager, the gateway ip status under the new IP range R2 is free; the gateway ip status under the old IP range R1 is activated. And when deleting the subnet failed, it throws the gateway port not found exception
> 
> @chenpiaoping I saw your fix in PR #536 for subnet mgr, which should address issue #523 for Subnet Mgr. For Issue #522, were you able to reproduce the issue following the above steps?

The results of the third step are as follows:
1.There are two ip range, the new one is: 0418e219-111c-4af2-b922-a316806e200c, the old one is : a0821e49-f749-47c1-b626-b5bed68e5620
[{"id":"0418e219-111c-4af2-b922-a316806e200c","vpc_id":"vpc_id1","subnet_id":"subnet_id1","ip_version":4,"first_ip":"10.0.0.1","last_ip":"10.0.0.254","used_ips":0,"total_ips":254},{"id":"a0821e49-f749-47c1-b626-b5bed68e5620","vpc_id":"vpc_id1","subnet_id":"subnet_id1","ip_version":4,"first_ip":"10.0.0.1","last_ip":"10.0.0.254","used_ips":1,"total_ips":254}]
2.gateway port is in old ip range
[{"ip_version":4,"vpc_id":null,"subnet_id":null,"range_id":"a0821e49-f749-47c1-b626-b5bed68e5620","ip":"10.0.0.1","state":"activated"}]
3.gateway port is in new ip range
[]
