### ISSUE TITLE
[Subnet Mgr] Subnet deletion needs to clean up old ip range in Private IP Mgr

### ISSUE THREAD

**Issue by kevin-zhonghao** [futurewei-cloud/alcor#523]
**Description:**
When creating a subnet, it would also create a ip range for the subnet in private ip manager. The operation of subnet deletion doesn't call port mgr for range cleanup, therefore the old ip range still remains in cache of private ip manager.

**Comment by chenpiaoping** [comment]
Why call port-manager to clear rang instead of calling private-ip-manager?

**Comment by xieus** [comment]
> Why call port-manager to clear rang instead of calling private-ip-manager?

Range clean-up should go directly to private ip manager. There exists a typo in the issue description.

**Comment by chenpiaoping** [comment]
fixed by this PR: https://github.com/futurewei-cloud/alcor/pull/536
