### ISSUE TITLE
[RM] getOrCreateVpcRouter in RouterController.java need a flag to indicate if it requires to create a router  

### ISSUE THREAD

**Issue by cj-chung** [futurewei-cloud/alcor#646]
**Issue:**
The current implementation in `getOrCreateVpcRouter` will create a new router if VPC router is not exist. 
This causes query operation for a non-exist router will create a router.

**Suggestion:**
Add a flag (default=false) as an input argument in `getOrCreateVpcRouter`. 
If an API needs to create a vpc router, it can input `true` for this flag.
For other query operations (flag default value=false), it won't create a router if it's not exist.

**Comment by xieus** [comment]
Good suggestion. I think the fix is necessary and should be straightforward. I think @DavidLiu506 could take on this task easily.

**Comment by kevin-zhonghao** [comment]
Router controller:
1. getOrCreateVPCRouter 
-> rename as 'getVPCRoutercreate', and delete 'create' operation related part 

-> Add a new API 'createVPCRouter' 

2. getOrCreateSubnetRouteTable
-> rename as 'getSubnetRouteTable', and delete 'create' operation related part 

3. createNeutronSubnetRouteTable 
-> rename as 'createSubnetRouteTable'

4. getOrCreateVpcRouteTable
-> rename as 'getVpcRouteTable', and delete 'create' operation related part

-> Add a new API 'createVpcRouteTable'
