### ISSUE TITLE
[RM] Separate getOrCreateSubnetRouteTable into two APIs and consolidate POST with createNeutronSubnetRouteTable

### ISSUE THREAD

**Issue by cj-chung** [futurewei-cloud/alcor#654]
**Issue:**
We have `getOrCreateSubnetRouteTable` API in RM. It causes the query subnet routing table creating a new subnet default routing table from VPC. This is not a behavior we want.

**Solution:**
Separate `getOrCreateSubnetRouteTable` into two APIs: GET and POST, and consolidate POST with `createNeutronSubnetRouteTable` API.  

![image](https://user-images.githubusercontent.com/66383484/123844065-718ba200-d8c7-11eb-8834-ede5994e8f52.png)

**Comment by kevin-zhonghao** [comment]
Fix in PR#657

**Comment by DavidLiu506** [comment]
This is fixed in PR [RM] Separate getOrCreateSubnetRouteTable into two APIs and consolidate POST with createNeutronSubnetRouteTable,
