### ISSUE TITLE
[DPM] Setting VpcId for each goal state in DpmServiceImplV2

### ISSUE THREAD

**Issue by VanderChen** [futurewei-cloud/alcor#721]
In our design, Message Queue uses VPC as its topic. Thus, VPC ID needs to be set for each goal state. 
In this documentation, we explain where VPC IDs are set.
*This issue is solved in PR #695 *

1. `processPortConfiguration`

| Goal State Type |  |
| --- | --- |
| Unicast GS | vpcService.buildVpcStates() |
| Multicast GS | neighborService.buildNeighborStatesL2() \& neighborService.buildNeighborStatesL3() |

Since the GS building process is corresponding to each port, there is only one VPC. 

2. `processNeighborConfiguration`

| Goal State Type |  |
| --- | --- |
| Unicast GS | neighborService.buildNeighborStatesL3() |
| Multicast GS | neighborService.buildNeighborStatesL3() |

Different from the `buildNeighborStatesL3()`  in `processPortConfiguration`, the method we used is `buildNeighborStatesL3(NetworkConfiguration networkConfiguration, Map<String, UnicastGoalStateV2> unicastGoalStates, MulticastGoalStateV2 multicastGoalState)` which generate a map for unicast goalstates.

3. `processRouterConfiguration`

| Goal State Type |  |
| --- | --- |
| Unicast GS | subnetService.buildSubnetState() |
| Multicast GS | subnetService.buildSubnetState() |

**Comment by xieus** [comment]
Discuss with @VanderChen and @cj-chung.  James, Please help review this PR.

**Comment by cj-chung** [comment]
This is a good summary for vpcId update in PR #695.
